--- Makefile.am	2009-02-22 13:04:25.000000000 -0700
+++ Makefile.am.thomas	2009-08-03 22:00:03.000000000 -0700
@@ -85,7 +85,7 @@
 	horde.schema \
 	rfc2739.schema
 
-ldapschemadir = $(ldapserver_confdir)/schema
+ldapschemadir = $(ldapserver_schemadir)
 dist_ldapschema_DATA = $(ldapschema_FILES)
 
 
